version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-headless-python3-7"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-cq2a6ijqy2ps"
s3_prefix = "sam-headless-python3-7"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["SamHeadlessChromium=770085715007.dkr.ecr.us-east-1.amazonaws.com/samheadlesspython37461ff18e/samheadlesschromium6d96c937repo"]
